from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('add_user/', views.add_user, name='add_user'),
    path('admin_registration/', views.admin_registration, name='admin_registration'),
    path('authority/register-request', views.authority_registration, name='authority_register_request'),
    path('authority/register-request/', views.authority_registration, name='authority_register_request_slash'),
    path('authority_registration/', views.authority_registration, name='authority_registration'),
    path('login/', views.login, name='login'),
    path('accounts/social/sync/', views.social_auth_sync, name='social_auth_sync'),
    path('report_issues/', views.report_issue, name='report_issues'), 
    path('my_issues/', views.my_issues, name='my_issues'),
    path('issue/', views.issue_overview, name='issue_overview'),
    path('issue/<str:issue_id>/', views.issue_detail, name='issue_detail'),
    path('map_view/', views.map_view, name='map_view'),
    path('profile/', views.profile, name='profile'),
    path('notification/', views.notification, name='notification'),
    # path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('fetch_issue_admin/', views.fetch_issue_admin, name='fetch_issue_admin'),
    path('reports/', views.reports, name='reports'),
    path('priority-queue/', views.priority_queue, name='priority_queue'),
    path('work-orders/', views.work_orders, name='work_orders'),
    path('reports/performance/', views.reports_performance, name='reports_performance'),
    path('reports/analytics/', views.reports_analytics, name='reports_analytics'),
    path('reports/overview/', views.reports_overview, name='reports_overview'),
    path('reports/create/', views.create_report, name='create_report'),
    path('activity/', views.my_activity, name='my_activity'),
    path('reports/data/', views.reports_data, name='reports_data'),
    path('issue_management/', views.issue_management, name='issue_management'),
    path('user_detail/', views.User_detail, name='User_detail'),
    path('user_detail/export-pdf/', views.export_users_pdf, name='export_users_pdf'),
    path('train_issue_ml_model/', views.train_issue_ml_model, name='train_issue_ml_model'),
    path('ai-review/', views.ai_review_queue, name='ai-review'),
    path('api/ai-review/queue/', views.ai_review_queue_api, name='ai_review_queue_api'),
    path('api/ai-review/approve/', views.ai_review_approve_api, name='ai_review_approve_api'),
    path('api/ai-review/correct/', views.ai_review_correct_api, name='ai_review_correct_api'),
    path('api/ai-review/reject/', views.ai_review_reject_api, name='ai_review_reject_api'),
    path('api/ai-review/export/', views.ai_review_export_api, name='ai_review_export_api'),
    path('settings/', views.settings, name='settings'),
    path('Settings/', views.settings, name='Settings'),
    path('api/settings/', views.settings_get_api, name='settings_get_api'),
    path('api/settings/update/', views.settings_update_api, name='settings_update_api'),
    path('api/settings/reset/', views.settings_reset_api, name='settings_reset_api'),
    path('privacy/', views.privacy_policy, name='privacy_policy'),
    path('terms/', views.terms_of_service, name='terms_of_service'),
]
